image: Visual Studio 2017

version: 1.0.0+{build}

matrix:
  fast_finish: true

init:
  - git config --global core.autocrlf true

install:
  - pwsh: |
        Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
        Install-Module Pester

test_script:
  - pwsh: |
        Invoke-Pester -Show Summary -OutputFile test-results.xml
        $webClient = New-Object System.Net.WebClient
        $webClient.UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\test-results.xml))

build: off
